### ISSUE TITLE
Rubber Error

### ISSUE THREAD

**Issue by matharp** [aslushnikov/latex-online#17]
Hi,

I use the laton script to use the Latex-Online service. A couple of months ago, I used to use it on documents like [resume.zip](https://github.com/aslushnikov/latex-online/files/321831/resume.zip) without any issues. I have been getting the following error for a couple of months now:
```
Errors during compiling TeX document
Error: Traceback (most recent call last):
  File "/usr/bin/rubber", line 4, in <module>
    sys.exit(Main()(sys.argv[1:]))
  File "/usr/lib/python2.7/dist-packages/rubber/cmdline.py", line 319, in __call__
    return self.main(cmdline)
  File "/usr/lib/python2.7/dist-packages/rubber/cmdline.py", line 247, in main
    env.main.parse()
  File "/usr/lib/python2.7/dist-packages/rubber/converters/latex.py", line 710, in parse
    self.process(self.source())
  File "/usr/lib/python2.7/dist-packages/rubber/converters/latex.py", line 763, in process
    self.parse_file(file)
  File "/usr/lib/python2.7/dist-packages/rubber/converters/latex.py", line 741, in parse_file
    function(self.vars, *args)
  File "/usr/lib/python2.7/dist-packages/rubber/converters/latex.py", line 1037, in h_documentclass
    self.process(file)
  File "/usr/lib/python2.7/dist-packages/rubber/converters/latex.py", line 763, in process
    self.parse_file(file)
  File "/usr/lib/python2.7/dist-packages/rubber/converters/latex.py", line 741, in parse_file
    function(self.vars, *args)
TypeError: h_documentclass() takes exactly 4 arguments (3 given)
```
Thank you.

**Comment by aslushnikov** [comment]
This seems to be this bug: https://bugs.launchpad.net/rubber/+bug/1266912

Latex-online currently uses rubber v1.1 which is pretty old. I'll update it as I have some time (feel free to help!)

**Comment by aslushnikov** [comment]
Works for me now!

**Comment by matharp** [comment]
It's fixed. Thanks!
